0901/workshop/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('',views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name="update")

]

0901/workshop/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

0901/workshop/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles':articles
    }
    return render(request, 'articles/index.html', context)


def new(request):
    return render(request, 'articles/new.html')


def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article(title=title, content=content)
    article.save()
    return redirect('articles:detail', article.pk)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html',context)


def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article
    }
    return render(request,'articles/edit.html', context)


def update(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article(title=title, content=content)
    article.save()
    return redirect('articles:edit', article.pk)

0901/workshop/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Detail</h1>
<h2>{{ article.pk }}번째 글 </h2>
<hr>
<h2>제목: {{ article.title }} </h2>
<p>내용: {{ article.content }} </p>
<p>작성 시각: {{article.created_at }} </p>
<p>수정 시각: {{article.updated_at }} </p>
<hr>
<a href="{% url 'articles:edit' article.pk %}">EDIT</a><br>
<input type="submit" value="DELETE"><br>
<a href="{% url 'articles:index' %} ">[back]</a>
{% endblock content %}

0901/workshop/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1>EDIT</h1>
  <form action="{% url "articles:create" %}" method="POST">
    {% csrf_token %}
    <lable for="title">Title: </lable>
    <input type="text" name="title" id="title"><br>
    <lable for="content">CONTENT: </lable>
    <textarea name="content" id="content"> {{ article.content }} </textarea><br>
    <input type="submit"><br>
  </form>
    <a href="{% url 'articles:index' %} ">[back]</a>
    <hr>

{% endblock content %}

0901/workshop/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1><br>
  <br>
  <a href= "{% url 'articles:new' %}">NEW</a>
  <hr>
  {% for article in articles %}
    <p>글번호: {{ article.pk}} </p>
    <p>제목: {{ article.title }} </p>
    <p>내용: {{ article.content }} </p>
    <a href="{% url 'articles:detail' article.pk %} ">DETAIL</a>
    <hr>
  {% endfor %}

{% endblock content %}

0901/workshop/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>NEW</h1>
  <form action="{% url "articles:create" %}" method="POST">
    {% csrf_token %}
    <lable for="title">Title: </lable>
    <input type="text" name="title" id="title"><br>
    <lable for="content">CONTENT: </lable>
    <textarea name="content" id="content"> {{ article.content }} </textarea><br>
    <input type="submit" value="작성"><br>
  </form>
    <a href="{% url 'articles:index' %} ">[back]</a>
    <hr>

{% endblock content %}